export const LIST = "LIST_QUIZ";
export const LIST_SUCCESS = "LIST_QUIZ_SUCCESS";
export const LIST_FAILED = "LIST_QUIZ_FAILED";

export const ADD = "ADD_QUIZ";
export const ADD_SUCCESS = "ADD_QUIZ_SUCCESS";
export const ADD_FAILED = "ADD_QUIZ_FAILED";

export const EDIT = "EDIT_QUIZ";
export const EDIT_SUCCESS = "EDIT_QUIZ_SUCCESS";
export const EDIT_FAILED = "EDIT_QUIZ_FAILED";

export const DELETE = "DELETE_QUIZ";
export const DELETE_SUCCESS = "DELETE_QUIZ_SUCCESS";
export const DELETE_FAILED = "DELETE_QUIZ_FAILED";

export const DETAIL = "DETAIL_QUIZ";
export const DETAIL_SUCCESS = "DETAIL_QUIZ_SUCCESS";
export const DETAIL_FAILED = "DETAIL_QUIZ_FAILED";

export const SUBMIT = "SUBMIT_QUIZ";
export const SUBMIT_SUCCESS = "SUBMIT_QUIZ_SUCCESS";
export const SUBMIT_FAILED = "SUBMIT_QUIZ_FAILED";

export const RANK = "RANK_QUIZ";
export const RANK_SUCCESS = "RANK_QUIZ_SUCCESS";
export const RANK_FAILED = "RANK_QUIZ_FAILED";

export const HISTORY = "HISTORY_QUIZ";
export const HISTORY_SUCCESS = "HISTORY_QUIZ_SUCCESS";
export const HISTORY_FAILED = "HISTORY_QUIZ_FAILED";

export const RESET_DATA = "RESET_DATA_QUIZ";
export const RESET_SUBMIT = "RESET_SUBMIT_QUIZ";
