export const LIST = "LIST_QUESTION";
export const LIST_SUCCESS = "LIST_QUESTION_SUCCESS";
export const LIST_FAILED = "LIST_QUESTION_FAILED";

export const ADD = "ADD_QUESTION";
export const ADD_SUCCESS = "ADD_QUESTION_SUCCESS";
export const ADD_FAILED = "ADD_QUESTION_FAILED";

export const EDIT = "EDIT_QUESTION";
export const EDIT_SUCCESS = "EDIT_QUESTION_SUCCESS";
export const EDIT_FAILED = "EDIT_QUESTION_FAILED";

export const DELETE = "DELETE_QUESTION";
export const DELETE_SUCCESS = "DELETE_QUESTION_SUCCESS";
export const DELETE_FAILED = "DELETE_QUESTION_FAILED";

export const RESET_DATA = "RESET_DATA_QUESTION";
