export const ROUTES = {
  HOME_PAGE: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  // admin routes
  ADMIN_HOME_PAGE: "/admin",
  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_USER: "/admin/users",
  ADMIN_CATEGORY: "/admin/categories",
  ADMIN_ADD_CATEGORY: "/admin/add_category",
  ADMIN_UPDATE_CATEGORY: "/admin/update_category",
  ADMIN_TOPIC: "/admin/topics",
  ADMIN_LESSON: "/admin/lessons",
  ADMIN_QUESTION: "/admin/questions",
  ADMIN_QUIZ: "/admin/quiz",
  ADMIN_SIGNOUT: "/admin/singout",
  // user routes
  TOPIC: "/topics",
  USER_DETAIL: "/user-detail",
  LESSON: "/:id/lessons",
  QUIZ: "/quiz",
  START_QUIZ: "/start_quiz/:id",
  RESULT_QUIZ: "/result_quiz/:id",
  RANK_QUIZ: "/quiz/rank/:id",
};
