export const LIST = "LIST_CATEGORY";
export const LIST_SUCCESS = "LIST_CATEGORY_SUCCESS";
export const LIST_FAILED = "LIST_CATEGORY_FAILED";

export const ADD = "ADD_CATEGORY";
export const ADD_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_FAILED = "ADD_CATEGORY_FAILED";

export const EDIT = "EDIT_CATEGORY";
export const EDIT_SUCCESS = "EDIT_CATEGORY_SUCCESS";
export const EDIT_FAILED = "EDIT_CATEGORY_FAILED";

export const DELETE = "DELETE_CATEGORY";
export const DELETE_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_FAILED = "DELETE_CATEGORY_FAILED";

export const RESET_DATA = "RESET_DATA_CATEGORY";
