export const LIST = "LIST_LESSON";
export const LIST_SUCCESS = "LIST_LESSON_SUCCESS";
export const LIST_FAILED = "LIST_LESSON_FAILED";

export const ADD = "ADD_LESSON";
export const ADD_SUCCESS = "ADD_LESSON_SUCCESS";
export const ADD_FAILED = "ADD_LESSON_FAILED";

export const EDIT = "EDIT_LESSON";
export const EDIT_SUCCESS = "EDIT_LESSON_SUCCESS";
export const EDIT_FAILED = "EDIT_LESSON_FAILED";

export const DELETE = "DELETE_LESSON";
export const DELETE_SUCCESS = "DELETE_LESSON_SUCCESS";
export const DELETE_FAILED = "DELETE_LESSON_FAILED";

export const RESET_DATA = "RESET_DATA_LESSON";
